### ISSUE TITLE
feat(dart/transform): Fix detection of Injectable

### ISSUE THREAD

**Issue by kegluneq** [kegluneq/angular#10]
The method for checking whether we need to register a class is naive and needs to be much smarter. It probably needs to be configurable similar to how [package:di](https://github.com/angular/di.dart), and I'd like to have a mode we can run in that detects necessary transformer settings and surfaces them to the user. I have some code towards this goal that I'll link here once it's pushed.

See `_Tester` in `directive_processor/rewriter.dart` [here](https://github.com/kegluneq/angular/blob/master/modules/angular2/src/transform/directive_processor/rewriter.dart#L198) for the current implementation.

**Comment by kegluneq** [comment]
See https://github.com/kegluneq/angular/tree/compiler_bootstrap for a quickly thrown together method that crawls the import graph recording which files define which classes. This could be used to follow back `extends`, `implements`, and (maybe?) `with` directives to determine what is `@Injectable`.

**Comment by kegluneq** [comment]
@jakemac53 don't know if you're still interested, but with the refactoring happening to `Compiler` right now, I'm thinking we should wait before tackling change detectors. For now I've refocused on getting the transformer running on Travis - do you want to take a look here?

Thanks!

**Comment by jakemac53** [comment]
Looking at this now, also when setting up my tests I noticed you can't actually mixin Injectable because it has a constructor, so I will just be supporting `extends` and `implements`.

**Comment by jakemac53** [comment]
completed in https://github.com/angular/angular/commit/c65fd31e86718d8ea56250ea1108254173470543

**Comment by kegluneq** [comment]
Fixed by https://github.com/angular/angular/commit/01d5c2951376c9279e5913fb37d45341513b8ba0
